### ISSUE TITLE
dismod_at docker image requires VPN access

### ISSUE THREAD

**Issue by jmitchell** [ihmeuw/cascade#238]
From the docs:

> Download and run from the IHME Docker registry. This requires VPN access.:
> 
>     docker pull reg.ihme.washington.edu/dismod/dismod_at

Are you open to publishing the image somewhere public, like [Docker Hub](https://hub.docker.com/)? Alternatively, could you host the authoritative `Dockerfile` for building that image?

**Comment by adolgert** [comment]
That's doable. I can put a Dockerfile here that will build Dismod-AT. There is another script, called `dmdismod`, that mounts the sqlite db file and calls Dismod-AT inside the Docker image. It's now here:
https://github.com/ihmeuw/cascade/tree/develop/scripts/automation/dismod
