### ISSUE TITLE
Prior parameter, nu, may not be negative

### ISSUE THREAD

**Issue by adolgert** [ihmeuw/cascade#40]
https://github.com/ihmeuw/cascade/blob/e8776f8df293bae323bac35856df898cad8335e0/src/cascade/model/priors.py#L56

The comment is correct that it must be positive. The code is incorrect. It should be <= 0 as an error.

The same goes for the standard deviation. Can't have a standard deviation of zero.

**Comment by alec-deason** [comment]
Gah. Thanks

________________________________
